name: Build and Test Node.js Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Node setup (composite)
        uses: ./.github/actions/node-setup
        with:
          node-version: "20"

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
