name: CI (Caller)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# ↓↓↓ This is the part you asked about ↓↓↓
concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  call-ci:
    uses: awels-m/ci-workshop-node/.github/workflows/reusable-ci.yml@v1.2
    with:
      node: "20"
    secrets: inherit
