name: Reusable Node CI

on:
  workflow_call:
    inputs:
      node:
        description: "Node.js version to use"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]

    steps:
      - name: Check out caller repository
        uses: actions/checkout@v4

      - name: Node setup (composite)
        uses: ./.github/actions/node-setup
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

